### ISSUE TITLE
How should I implement an automatic handles in service?

### ISSUE THREAD

**Issue by Yon2068** [piotrekh/unit-of-work-core#1]
Thank you for the code!
How should I implement an automatic handles in service?

**Comment by piotrekh** [comment]
Hi, could you please elaborate on what you need and explain what you mean by saying 'automatic handles'?

**Comment by Yon2068** [comment]
Excuse me,
My English is poor,
I want to automatic  run SaveChange in ServiceClass.
How should I design service?

**Comment by piotrekh** [comment]
No worries. In simple cases (e.g. when you want to update an existing entity) you don't need to call SaveChanges because UnitOfWorkTransactionFilter will do this for you at the end of the request (take a look at the filter [here](https://github.com/piotrekh/unit-of-work-core/blob/master/UnitOfWorkCore.AspNetCore/Filters/UnitOfWorkTransactionFilter.cs) and see that it calls [_uow.CommitTransaction](https://github.com/piotrekh/unit-of-work-core/blob/master/UnitOfWorkCore/UnitOfWork.cs) which actually calls Context.SaveChanges). However, you might still need to call SaveChanges manually e.g. when you want to save a new entity to database and instantly retrieve its's id that is an identity column in the database, for later use (that's what I did in one of the sample projects). In such case you have no other choice but call SaveChanges yourself in your service class. Let me know if this explanation helps.

**Comment by Yon2068** [comment]
Sorry, I have been busy recently, so I just saw your reply.
In the Service of ABP Framework, SaveChange() can be automatic.
How does it do that?

**Comment by Yon2068** [comment]
I think,
Service can be like MVC,
It Implemented a filter to run SaveChange().
What do you think?

**Comment by piotrekh** [comment]
SaveChanges() is already automatically called in my code in the UnitOfWorkTransactionFilter. That's exactly what you are talking about - see the links in my post above. However, you cannot always rely on this mechanism, which I also explained in the previous post (sometimes you need to call it manually).

**Comment by Yon2068** [comment]
emmm....
Forgive me for not being clear.
Because I'm developing to use DDD design pattern.
Do you have any good ideas about designing filter in DDD service?

**Comment by piotrekh** [comment]
It doesn't matter what design/architecture pattern you use (it can be DDD, CQRS, you can use repositories or not etc.), as long as you register the UnitOfWorkTransactionFilter in ASP.NET project accordingly to the instructions in readme file, the SaveChanges() method will be called automatically.
